version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nodenet
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: sh -c '/usr/bin/wait-for db:3306 -t 20 -- node index.js'
    depends_on:
      - db    
    networks:
      - nodenet
    tty: true
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=dbnode
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    tty: true
    volumes:
      - ./db:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  node:
    driver: local      
  db:
    driver: local      
  scripts:
    driver: local      
  nginx:
    driver: local      

networks:
  nodenet: 
    driver: bridge
